In [6]:
from bs4 import BeautifulSoup
import json
from tqdm import tqdm

In [2]:
# Load your HTML (the full <li> you posted)
with open("wnba_prices.html", "r", encoding="utf-8") as f:
    html_content = f.read()

In [3]:
html_content[:1000]

'<div class="layoutPresenters__OuterMargin-sc-f4172277-1 lnYDpf"><hr class="layoutPresenters__Divider-sc-f4172277-6 gSLyJh"><div class="layoutPresenters__SectionSpacer-sc-f4172277-7 XclfL"><div class="layoutPresenters__Columns-sc-f4172277-2 ksBaUz"><main class="layoutPresenters__MainColumn-sc-f4172277-4 fmxXyL"><div class="layoutPresenters__HeadingRow-sc-f4172277-5 edMHfI"><h2 class="Category__StyledH2-sc-63d0a570-0 kEPKwi">All WNBA Games</h2></div><div><ul class="EventList__BaseEventList-sc-9ea8f928-2 dASQDu"><li data-testid="event-17411342" class="TwoRowEventTitleEventItem__EventItemWrapper-sc-52143443-12 hxKrwI"><a data-testid="event-link-17411342" target="_self" class="TwoRowEventTitleEventItem__ItemLink-sc-52143443-3 ebXXXM" href="/las-vegas-aces-tickets/wnba/2025-05-02-7-pm/17411342"><span class="TwoRowEventTitleEventItem__HiddenScreenReaderDescription-sc-52143443-0 hROKjX"> Find tickets from 20 dollars to Preseason: Las Vegas Aces vs Dallas Wings on Friday May 2 at 7:00 pm at Pur'

In [7]:
soup = BeautifulSoup(html_content, "html.parser")


events = []

# Find all event list items
event_items = soup.find_all("li", {"class": "TwoRowEventTitleEventItem__EventItemWrapper-sc-52143443-12"})

for item in tqdm(event_items):
    date = item.find("p", {"data-testid": "date"})
    time = item.find("p", {"data-testid": "time"})
    title = item.find("p", {"data-testid": "event-item-title"})
    description = item.find("p", {"data-testid": "description"})
    link_tag = item.find("a", {"data-testid": lambda x: x and x.startswith("event-link-")})

    if description:
        # Try to parse the location and price from the description text
        desc_text = description.get_text(separator="·")
        parts = [part.strip() for part in desc_text.split('·')]

        if len(parts) >= 2:
            price = parts[0]
            location = " · ".join(parts[1:])  # Combine if there are multiple '·'s
        else:
            price = None
            location = None
    else:
        price = None
        location = None

    event_info = {
        "date": date.get_text(strip=True) if date else None,
        "time": time.get_text(strip=True) if time else None,
        "title": title.get_text(strip=True) if title else None,
        "price": price,
        "location": location,
        "url": link_tag['href'] if link_tag else None
    }

    events.append(event_info)

100%|██████████| 302/302 [00:00<00:00, 19473.90it/s]

{'date': 'May 2', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Las Vegas Aces vs Dallas Wings', 'price': '$20', 'location': ' ·  · Purcell Pavilion at the Joyce Center ·  ·  · Notre Dame, IN', 'url': '/las-vegas-aces-tickets/wnba/2025-05-02-7-pm/17411342'}
{'date': 'May 2', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Brazil Womens Basketball National Team at Chicago Sky', 'price': '$18', 'location': ' ·  · Pete Maravich Assembly Center ·  ·  · Baton Rouge, LA', 'url': '/chicago-sky-tickets/wnba/2025-05-02-7-pm/17367444'}
{'date': 'May 3', 'time': 'Sat · 1:00pm', 'title': 'Preseason: Washington Mystics at Indiana Fever', 'price': '$10', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-03-1-pm/17317444'}
{'date': 'May 4', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Brazil Womens Basketball National Team at Indiana Fever', 'price': '$146', 'location': ' ·  · Carver-Hawkeye Arena ·  ·  · Iowa City, IA', 'url': '/indiana-fever-tickets/wnba/2025-05-04-3-pm/17365932'}
{'date': 'May 4', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Connecticut Sun at Seattle Storm', 'price': '$8', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-04-3-pm/17429790'}
{'date': 'May 6', 'time': 'Tue · 6:00pm', 'title': 'Preseason: Minnesota Lynx at Chicago Sky', 'price': '$25', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-06-6-pm/17425039'}
{'date': 'May 6', 'time': 'Tue · 7:00pm', 'title': 'Preseason: Phoenix Mercury at Las Vegas Aces', 'price': '$6', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-06-7-pm/17391518'}
{'date': 'May 6', 'time': 'Tue · 7:00pm', 'title': 'Preseason: Los Angeles Sparks at Golden State Valkyries', 'price': '$26', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-06-7-pm/17392020'}
{'date': 'May 7', 'time': 'Wed · 11:30am', 'title': 'Preseason: Atlanta Dream at Washington Mystics', 'price': '$16', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-07-11-30-am/17324816'}
{'date': 'May 9', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Connecticut Sun at New York Liberty', 'price': '$25', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-09-7-pm/17417329'}
{'date': 'May 10', 'time': 'Sat · 3:00pm', 'title': 'Preseason: Indiana Fever at Atlanta Dream', 'price': '$67', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-10-3-pm/17324814'}
{'date': 'May 11', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Golden State Valkyries at Phoenix Mercury', 'price': '$19', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-11-3-pm/17409726'}
{'date': 'May 12', 'time': 'Mon · 7:00pm', 'title': 'Toyota Antelopes at New York Liberty (Exhibition)', 'price': '$15', 'location': ' ·  · Matthew Knight Arena ·  ·  · Eugene, OR', 'url': '/new-york-liberty-tickets/wnba/2025-05-12-7-pm/17417331'}
{'date': 'May 16', 'time': 'Fri · 6:30pm', 'title': 'Minnesota Lynx at Dallas Wings', 'price': '$57', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-16-6-30-pm/17290245'}
{'date': 'May 16', 'time': 'Fri · 7:00pm', 'title': 'Los Angeles Sparks at Golden State Valkyries', 'price': '$109', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-16-7-pm/17290288'}
{'date': 'May 16', 'time': 'Fri · 7:30pm', 'title': 'Atlanta Dream at Washington Mystics', 'price': '$27', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-16-7-30-pm/17289837'}
{'date': 'May 17', 'time': 'Sat · 1:00pm', 'title': 'Las Vegas Aces at New York Liberty', 'price': '$83', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-17-1-pm/17289838'}
{'date': 'May 17', 'time': 'Sat · 3:00pm', 'title': 'Chicago Sky at Indiana Fever', 'price': '$65', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-17-3-pm/17290332'}
{'date': 'May 17', 'time': 'Sat · 7:00pm', 'title': 'Seattle Storm at Phoenix Mercury', 'price': '$18', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-17-7-pm/17289840'}
{'date': 'May 18', 'time': 'Sun · 1:00pm', 'title': 'Washington Mystics at Connecticut Sun', 'price': '$19', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-18-1-pm/17290201'}
{'date': 'May 18', 'time': 'Sun · 3:00pm', 'title': 'Minnesota Lynx at Los Angeles Sparks', 'price': '$38', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-18-3-pm/17289839'}
{'date': 'May 19', 'time': 'Mon · 7:00pm', 'title': 'Seattle Storm at Dallas Wings', 'price': '$42', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-19-7-pm/17290247'}
{'date': 'May 20', 'time': 'Tue · 7:00pm', 'title': 'Las Vegas Aces at Connecticut Sun', 'price': '$17', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-20-7-pm/17290203'}
{'date': 'May 20', 'time': 'Tue · 7:00pm', 'title': 'Atlanta Dream at Indiana Fever', 'price': '$11', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-20-7-pm/17290335'}
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Dallas Wings at Minnesota Lynx', 'price': '$99', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-21-7-pm/17289841'}
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Los Angeles Sparks at Phoenix Mercury', 'price': '$16', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-21-7-pm/17289842'}
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Washington Mystics at Golden State Valkyries', 'price': '$37', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-21-7-pm/17290291'}
{'date': 'May 22', 'time': 'Thu · 7:00pm', 'title': 'New York Liberty at Chicago Sky', 'price': '$53', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-22-7-pm/17290157'}
{'date': 'May 22', 'time': 'Thu · 7:30pm', 'title': 'Indiana Fever at Atlanta Dream', 'price': '$47', 'location': ' ·  · State Farm Arena ·  ·  · Atlanta, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-22-7-30-pm/17429237'}
{'date': 'May 23', 'time': 'Fri · 6:30pm', 'title': 'Connecticut Sun at Minnesota Lynx', 'price': '$104', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-23-6-30-pm/17289850'}
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Phoenix Mercury at Seattle Storm', 'price': '$18', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-23-7-pm/17289851'}
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Golden State Valkyries at Los Angeles Sparks', 'price': '$33', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-23-7-pm/17289849'}
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Washington Mystics at Las Vegas Aces', 'price': '$14', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-23-7-pm/17290377'}
{'date': 'May 24', 'time': 'Sat · 1:00pm', 'title': 'New York Liberty at Indiana Fever', 'price': '$48', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-24-1-pm/17290337'}
{'date': 'May 24', 'time': 'Sat · 3:00pm', 'title': 'Dallas Wings at Atlanta Dream', 'price': '$165', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-24-3-pm/17290117'}
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Washington Mystics at Phoenix Mercury', 'price': '$15', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-25-3-pm/17289853'}
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Las Vegas Aces at Seattle Storm', 'price': '$20', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-25-3-pm/17289854'}
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Chicago Sky at Los Angeles Sparks', 'price': '$53', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-25-3-pm/17289852'}
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Connecticut Sun at Atlanta Dream', 'price': '$25', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-25-3-pm/17290115'}
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Golden State Valkyries at New York Liberty', 'price': '$21', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-27-7-pm/17289863'}
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Dallas Wings at Connecticut Sun', 'price': '$86', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-27-7-pm/17290204'}
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Atlanta Dream at Los Angeles Sparks', 'price': '$24', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-27-7-pm/17289861'}
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Chicago Sky at Phoenix Mercury', 'price': '$28', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-27-7-pm/17289867'}
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Seattle Storm at Minnesota Lynx', 'price': '$97', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-27-7-pm/17289862'}
{'date': 'May 28', 'time': 'Wed · 7:30pm', 'title': 'Indiana Fever at Washington Mystics', 'price': '$124', 'location': ' ·  · CFG Bank Arena ·  ·  · Baltimore, MD', 'url': '/washington-mystics-tickets/wnba/2025-05-28-7-30-pm/17289868'}
{'date': 'May 29', 'time': 'Thu · 7:00pm', 'title': 'Golden State Valkyries at New York Liberty', 'price': '$19', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-29-7-pm/17289869'}
{'date': 'May 29', 'time': 'Thu · 7:00pm', 'title': 'Dallas Wings at Chicago Sky', 'price': '$90', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-29-7-pm/17290156'}
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Los Angeles Sparks at Las Vegas Aces', 'price': '$22', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-30-7-pm/17290378'}
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Minnesota Lynx at Phoenix Mercury', 'price': '$8', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-30-7-pm/17289873'}
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Atlanta Dream at Seattle Storm', 'price': '$18', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-30-7-pm/17289874'}
{'date': 'May 30', 'time': 'Fri · 7:30pm', 'title': 'Connecticut Sun at Indiana Fever', 'price': '$21', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-30-7-30-pm/17290338'}
{'date': 'May 30', 'time': 'Fri · 7:30pm', 'title': 'New York Liberty at Washington Mystics', 'price': '$40', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-30-7-30-pm/17289876'}
{'date': 'May 31', 'time': 'Sat · 7:00pm', 'title': 'Chicago Sky at Dallas Wings', 'price': '$89', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-31-7-pm/17290248'}
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Las Vegas Aces at Seattle Storm', 'price': '$20', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-01-3-pm/17289881'}
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Phoenix Mercury at Los Angeles Sparks', 'price': '$32', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-06-01-3-pm/17289879'}
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Connecticut Sun at New York Liberty', 'price': '$36', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-06-01-3-pm/17289880'}
{'date': 'Jun 1', 'time': 'Sun · 5:30pm', 'title': 'Commissioners Cup: Minnesota Lynx at Golden State Valkyries', 'price': '$34', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-01-5-30-pm/17290293'}
{'date': 'Jun 3', 'time': 'Tue · 6:30pm', 'title': 'Commissioners Cup: Dallas Wings at Seattle Storm', 'price': '$47', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-03-6-30-pm/17289887'}
{'date': 'Jun 3', 'time': 'Tue · 7:00pm', 'title': 'Commissioners Cup: Washington Mystics at Indiana Fever', 'price': '$14', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-06-03-7-pm/17290339'}
{'date': 'Jun 3', 'time': 'Tue · 7:00pm', 'title': 'Commisioners Cup: Phoenix Mercury at Minnesota Lynx', 'price': '$102', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-06-03-7-pm/17289885'}
{'date': 'Jun 5', 'time': 'Thu · 7:00pm', 'title': 'Commissioners Cup: Golden State Valkyries at Phoenix Mercury', 'price': '$11', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-05-7-pm/17289888'}
{'date': 'Jun 5', 'time': 'Thu · 7:30pm', 'title': 'Commissioners Cup: New York Liberty at Washington Mystics', 'price': '$65', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-06-05-7-30-pm/17289891'}
{'date': 'Jun 6', 'time': 'Fri · 7:30pm', 'title': 'Commissioners Cup: Atlanta Dream at Connecticut Sun', 'price': '$14', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-06-06-7-30-pm/17290205'}
{'date': 'Jun 6', 'time': 'Fri · 8:30pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Dallas Wings', 'price': '$60', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-06-06-8-30-pm/17290249'}
{'date': 'Jun 7', 'time': 'Sat · 12:00pm', 'title': 'Commissioners Cup: Las Vegas Aces at Golden State Valkyries', 'price': '$53', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-07-12-pm/17290295'}
{'date': 'Jun 7', 'time': 'Sat · 7:00pm', 'title': 'Commissioners Cup: Seattle Storm at Phoenix Mercury', 'price': '$18', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-07-7-pm/17289893'}
{'date': 'Jun 7', 'time': 'Sat · 7:00pm', 'title': 'Commissioners Cup: Indiana Fever at Chicago Sky', 'price': '$77', 'location': ' ·  · United Center ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-06-07-7-pm/17290160'}
{'date': 'Jun 8', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Minnesota Lynx at Dallas Wings', 'price': '$51', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-06-08-3-pm/17290250'}
{'date': 'Jun 8', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Connecticut Sun at Washington Mystics', 'price': '$50', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-06-08-3-pm/17289894'}
{'date': 'Jun 9', 'time': 'Mon · 7:00pm', 'title': 'Commissioners Cup: Golden State Valkyries at Los Angeles Sparks', 'price': '$28', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-06-09-7-pm/17289896'}
{'date': 'Jun 10', 'time': 'Tue · 7:30pm', 'title': 'Commissioners Cup: Indiana Fever at Atlanta Dream', 'price': '$140', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-06-10-7-30-pm/17290119'}
{'date': 'Jun 10', 'time': 'Tue · 8:00pm', 'title': 'Commissioners Cup: Chicago Sky at New York Liberty', 'price': '$43', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-06-10-8-pm/17289900'}
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Minnesota Lynx at Seattle Storm', 'price': '$16', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-11-7-pm/17289901'}
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Las Vegas Aces', 'price': '$10', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-06-11-7-pm/17290380'}
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Dallas Wings at Phoenix Mercury', 'price': '$36', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-11-7-pm/17289899'}
{'date': 'Jun 13', 'time': 'Fri · 7:00pm', 'title': 'Commissioners Cup: Dallas Wings at Las Vegas Aces', 'price': '$32', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-06-13-7-pm/17290383'}
{'date': 'Jun 13', 'time': 'Fri · 7:30pm', 'title': 'Commissioners Cup: Chicago Sky at Atlanta Dream', 'price': '$76', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-06-13-7-30-pm/17290116'}
{'date': 'Jun 14', 'time': 'Sat · 12:00pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Minnesota Lynx', 'price': '$86', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-06-14-12-pm/17289905'}
{'date': 'Jun 14', 'time': 'Sat · 3:00pm', 'title': 'Commissioners Cup: New York Liberty at Indiana Fever', 'price': '$42', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-06-14-3-pm/17290343'}
{'date': 'Jun 14', 'time': 'Sat · 5:30pm', 'title': 'Commissioners Cup: Seattle Storm at Golden State Valkyries', 'price': '$33', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-14-5-30-pm/17290297'}
{'date': 'Jun 15', 'time': 'Sun · 12:00pm', 'title': 'Commissioners Cup: Chicago Sky at Connecticut Sun', 'price': '$21', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-06-15-12-pm/17290209'}

In [9]:
# Print extracted events
for event in events:
    print(event)
    print('---')

{'date': 'May 2', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Las Vegas Aces vs Dallas Wings', 'price': '$20', 'location': ' ·  · Purcell Pavilion at the Joyce Center ·  ·  · Notre Dame, IN', 'url': '/las-vegas-aces-tickets/wnba/2025-05-02-7-pm/17411342'}
---
{'date': 'May 2', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Brazil Womens Basketball National Team at Chicago Sky', 'price': '$18', 'location': ' ·  · Pete Maravich Assembly Center ·  ·  · Baton Rouge, LA', 'url': '/chicago-sky-tickets/wnba/2025-05-02-7-pm/17367444'}
---
{'date': 'May 3', 'time': 'Sat · 1:00pm', 'title': 'Preseason: Washington Mystics at Indiana Fever', 'price': '$10', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-03-1-pm/17317444'}
---
{'date': 'May 4', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Brazil Womens Basketball National Team at Indiana Fever', 'price': '$146', 'location': ' ·  · Carver-Hawkeye Arena ·  ·  · Iowa City, IA', 'url': '/indiana-fever-tickets/wnba/2025-05-04-3-pm/17365932'}
---
{'date': 'May 4', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Connecticut Sun at Seattle Storm', 'price': '$8', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-04-3-pm/17429790'}
---
{'date': 'May 6', 'time': 'Tue · 6:00pm', 'title': 'Preseason: Minnesota Lynx at Chicago Sky', 'price': '$25', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-06-6-pm/17425039'}
---
{'date': 'May 6', 'time': 'Tue · 7:00pm', 'title': 'Preseason: Phoenix Mercury at Las Vegas Aces', 'price': '$6', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-06-7-pm/17391518'}
---
{'date': 'May 6', 'time': 'Tue · 7:00pm', 'title': 'Preseason: Los Angeles Sparks at Golden State Valkyries', 'price': '$26', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-06-7-pm/17392020'}
---
{'date': 'May 7', 'time': 'Wed · 11:30am', 'title': 'Preseason: Atlanta Dream at Washington Mystics', 'price': '$16', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-07-11-30-am/17324816'}
---
{'date': 'May 9', 'time': 'Fri · 7:00pm', 'title': 'Preseason: Connecticut Sun at New York Liberty', 'price': '$25', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-09-7-pm/17417329'}
---
{'date': 'May 10', 'time': 'Sat · 3:00pm', 'title': 'Preseason: Indiana Fever at Atlanta Dream', 'price': '$67', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-10-3-pm/17324814'}
---
{'date': 'May 11', 'time': 'Sun · 3:00pm', 'title': 'Preseason: Golden State Valkyries at Phoenix Mercury', 'price': '$19', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-11-3-pm/17409726'}
---
{'date': 'May 12', 'time': 'Mon · 7:00pm', 'title': 'Toyota Antelopes at New York Liberty (Exhibition)', 'price': '$15', 'location': ' ·  · Matthew Knight Arena ·  ·  · Eugene, OR', 'url': '/new-york-liberty-tickets/wnba/2025-05-12-7-pm/17417331'}
---
{'date': 'May 16', 'time': 'Fri · 6:30pm', 'title': 'Minnesota Lynx at Dallas Wings', 'price': '$57', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-16-6-30-pm/17290245'}
---
{'date': 'May 16', 'time': 'Fri · 7:00pm', 'title': 'Los Angeles Sparks at Golden State Valkyries', 'price': '$109', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-16-7-pm/17290288'}
---
{'date': 'May 16', 'time': 'Fri · 7:30pm', 'title': 'Atlanta Dream at Washington Mystics', 'price': '$27', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-16-7-30-pm/17289837'}
---
{'date': 'May 17', 'time': 'Sat · 1:00pm', 'title': 'Las Vegas Aces at New York Liberty', 'price': '$83', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-17-1-pm/17289838'}
---
{'date': 'May 17', 'time': 'Sat · 3:00pm', 'title': 'Chicago Sky at Indiana Fever', 'price': '$65', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-17-3-pm/17290332'}
---
{'date': 'May 17', 'time': 'Sat · 7:00pm', 'title': 'Seattle Storm at Phoenix Mercury', 'price': '$18', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-17-7-pm/17289840'}
---
{'date': 'May 18', 'time': 'Sun · 1:00pm', 'title': 'Washington Mystics at Connecticut Sun', 'price': '$19', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-18-1-pm/17290201'}
---
{'date': 'May 18', 'time': 'Sun · 3:00pm', 'title': 'Minnesota Lynx at Los Angeles Sparks', 'price': '$38', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-18-3-pm/17289839'}
---
{'date': 'May 19', 'time': 'Mon · 7:00pm', 'title': 'Seattle Storm at Dallas Wings', 'price': '$42', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-19-7-pm/17290247'}
---
{'date': 'May 20', 'time': 'Tue · 7:00pm', 'title': 'Las Vegas Aces at Connecticut Sun', 'price': '$17', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-20-7-pm/17290203'}
---
{'date': 'May 20', 'time': 'Tue · 7:00pm', 'title': 'Atlanta Dream at Indiana Fever', 'price': '$11', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-20-7-pm/17290335'}
---
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Dallas Wings at Minnesota Lynx', 'price': '$99', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-21-7-pm/17289841'}
---
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Los Angeles Sparks at Phoenix Mercury', 'price': '$16', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-21-7-pm/17289842'}
---
{'date': 'May 21', 'time': 'Wed · 7:00pm', 'title': 'Washington Mystics at Golden State Valkyries', 'price': '$37', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-05-21-7-pm/17290291'}
---
{'date': 'May 22', 'time': 'Thu · 7:00pm', 'title': 'New York Liberty at Chicago Sky', 'price': '$53', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-22-7-pm/17290157'}
---
{'date': 'May 22', 'time': 'Thu · 7:30pm', 'title': 'Indiana Fever at Atlanta Dream', 'price': '$47', 'location': ' ·  · State Farm Arena ·  ·  · Atlanta, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-22-7-30-pm/17429237'}
---
{'date': 'May 23', 'time': 'Fri · 6:30pm', 'title': 'Connecticut Sun at Minnesota Lynx', 'price': '$104', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-23-6-30-pm/17289850'}
---
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Phoenix Mercury at Seattle Storm', 'price': '$18', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-23-7-pm/17289851'}
---
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Golden State Valkyries at Los Angeles Sparks', 'price': '$33', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-23-7-pm/17289849'}
---
{'date': 'May 23', 'time': 'Fri · 7:00pm', 'title': 'Washington Mystics at Las Vegas Aces', 'price': '$14', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-23-7-pm/17290377'}
---
{'date': 'May 24', 'time': 'Sat · 1:00pm', 'title': 'New York Liberty at Indiana Fever', 'price': '$48', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-24-1-pm/17290337'}
---
{'date': 'May 24', 'time': 'Sat · 3:00pm', 'title': 'Dallas Wings at Atlanta Dream', 'price': '$165', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-24-3-pm/17290117'}
---
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Washington Mystics at Phoenix Mercury', 'price': '$15', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-25-3-pm/17289853'}
---
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Las Vegas Aces at Seattle Storm', 'price': '$20', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-25-3-pm/17289854'}
---
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Chicago Sky at Los Angeles Sparks', 'price': '$53', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-25-3-pm/17289852'}
---
{'date': 'May 25', 'time': 'Sun · 3:00pm', 'title': 'Connecticut Sun at Atlanta Dream', 'price': '$25', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-05-25-3-pm/17290115'}
---
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Golden State Valkyries at New York Liberty', 'price': '$21', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-27-7-pm/17289863'}
---
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Dallas Wings at Connecticut Sun', 'price': '$86', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-05-27-7-pm/17290204'}
---
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Atlanta Dream at Los Angeles Sparks', 'price': '$24', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-05-27-7-pm/17289861'}
---
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Chicago Sky at Phoenix Mercury', 'price': '$28', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-27-7-pm/17289867'}
---
{'date': 'May 27', 'time': 'Tue · 7:00pm', 'title': 'Seattle Storm at Minnesota Lynx', 'price': '$97', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-05-27-7-pm/17289862'}
---
{'date': 'May 28', 'time': 'Wed · 7:30pm', 'title': 'Indiana Fever at Washington Mystics', 'price': '$124', 'location': ' ·  · CFG Bank Arena ·  ·  · Baltimore, MD', 'url': '/washington-mystics-tickets/wnba/2025-05-28-7-30-pm/17289868'}
---
{'date': 'May 29', 'time': 'Thu · 7:00pm', 'title': 'Golden State Valkyries at New York Liberty', 'price': '$19', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-05-29-7-pm/17289869'}
---
{'date': 'May 29', 'time': 'Thu · 7:00pm', 'title': 'Dallas Wings at Chicago Sky', 'price': '$90', 'location': ' ·  · Wintrust Arena ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-05-29-7-pm/17290156'}
---
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Los Angeles Sparks at Las Vegas Aces', 'price': '$22', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-05-30-7-pm/17290378'}
---
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Minnesota Lynx at Phoenix Mercury', 'price': '$8', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-05-30-7-pm/17289873'}
---
{'date': 'May 30', 'time': 'Fri · 7:00pm', 'title': 'Atlanta Dream at Seattle Storm', 'price': '$18', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-05-30-7-pm/17289874'}
---
{'date': 'May 30', 'time': 'Fri · 7:30pm', 'title': 'Connecticut Sun at Indiana Fever', 'price': '$21', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-05-30-7-30-pm/17290338'}
---
{'date': 'May 30', 'time': 'Fri · 7:30pm', 'title': 'New York Liberty at Washington Mystics', 'price': '$40', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-05-30-7-30-pm/17289876'}
---
{'date': 'May 31', 'time': 'Sat · 7:00pm', 'title': 'Chicago Sky at Dallas Wings', 'price': '$89', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-05-31-7-pm/17290248'}
---
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Las Vegas Aces at Seattle Storm', 'price': '$20', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-01-3-pm/17289881'}
---
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Phoenix Mercury at Los Angeles Sparks', 'price': '$32', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-06-01-3-pm/17289879'}
---
{'date': 'Jun 1', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Connecticut Sun at New York Liberty', 'price': '$36', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-06-01-3-pm/17289880'}
---
{'date': 'Jun 1', 'time': 'Sun · 5:30pm', 'title': 'Commissioners Cup: Minnesota Lynx at Golden State Valkyries', 'price': '$34', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-01-5-30-pm/17290293'}
---
{'date': 'Jun 3', 'time': 'Tue · 6:30pm', 'title': 'Commissioners Cup: Dallas Wings at Seattle Storm', 'price': '$47', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-03-6-30-pm/17289887'}
---
{'date': 'Jun 3', 'time': 'Tue · 7:00pm', 'title': 'Commissioners Cup: Washington Mystics at Indiana Fever', 'price': '$14', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-06-03-7-pm/17290339'}
---
{'date': 'Jun 3', 'time': 'Tue · 7:00pm', 'title': 'Commisioners Cup: Phoenix Mercury at Minnesota Lynx', 'price': '$102', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-06-03-7-pm/17289885'}
---
{'date': 'Jun 5', 'time': 'Thu · 7:00pm', 'title': 'Commissioners Cup: Golden State Valkyries at Phoenix Mercury', 'price': '$11', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-05-7-pm/17289888'}
---
{'date': 'Jun 5', 'time': 'Thu · 7:30pm', 'title': 'Commissioners Cup: New York Liberty at Washington Mystics', 'price': '$65', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-06-05-7-30-pm/17289891'}
---
{'date': 'Jun 6', 'time': 'Fri · 7:30pm', 'title': 'Commissioners Cup: Atlanta Dream at Connecticut Sun', 'price': '$14', 'location': ' ·  · Mohegan Sun Arena ·  ·  · Uncasville, CT', 'url': '/connecticut-sun-tickets/wnba/2025-06-06-7-30-pm/17290205'}
---
{'date': 'Jun 6', 'time': 'Fri · 8:30pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Dallas Wings', 'price': '$60', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-06-06-8-30-pm/17290249'}
---
{'date': 'Jun 7', 'time': 'Sat · 12:00pm', 'title': 'Commissioners Cup: Las Vegas Aces at Golden State Valkyries', 'price': '$53', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-07-12-pm/17290295'}
---
{'date': 'Jun 7', 'time': 'Sat · 7:00pm', 'title': 'Commissioners Cup: Seattle Storm at Phoenix Mercury', 'price': '$18', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-07-7-pm/17289893'}
---
{'date': 'Jun 7', 'time': 'Sat · 7:00pm', 'title': 'Commissioners Cup: Indiana Fever at Chicago Sky', 'price': '$77', 'location': ' ·  · United Center ·  ·  · Chicago, IL', 'url': '/chicago-sky-tickets/wnba/2025-06-07-7-pm/17290160'}
---
{'date': 'Jun 8', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Minnesota Lynx at Dallas Wings', 'price': '$51', 'location': ' ·  · College Park Center ·  ·  · Arlington, TX', 'url': '/dallas-wings-tickets/wnba/2025-06-08-3-pm/17290250'}
---
{'date': 'Jun 8', 'time': 'Sun · 3:00pm', 'title': 'Commissioners Cup: Connecticut Sun at Washington Mystics', 'price': '$50', 'location': ' ·  · CareFirst Arena ·  ·  · Washington, DC', 'url': '/washington-mystics-tickets/wnba/2025-06-08-3-pm/17289894'}
---
{'date': 'Jun 9', 'time': 'Mon · 7:00pm', 'title': 'Commissioners Cup: Golden State Valkyries at Los Angeles Sparks', 'price': '$28', 'location': ' ·  · Crypto.com Arena ·  ·  · Los Angeles, CA', 'url': '/los-angeles-sparks-tickets/wnba/2025-06-09-7-pm/17289896'}
---
{'date': 'Jun 10', 'time': 'Tue · 7:30pm', 'title': 'Commissioners Cup: Indiana Fever at Atlanta Dream', 'price': '$140', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-06-10-7-30-pm/17290119'}
---
{'date': 'Jun 10', 'time': 'Tue · 8:00pm', 'title': 'Commissioners Cup: Chicago Sky at New York Liberty', 'price': '$43', 'location': ' ·  · Barclays Center ·  ·  · Brooklyn, NY', 'url': '/new-york-liberty-tickets/wnba/2025-06-10-8-pm/17289900'}
---
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Minnesota Lynx at Seattle Storm', 'price': '$16', 'location': ' ·  · Climate Pledge Arena ·  ·  · Seattle, WA', 'url': '/seattle-storm-tickets/wnba/2025-06-11-7-pm/17289901'}
---
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Las Vegas Aces', 'price': '$10', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-06-11-7-pm/17290380'}
---
{'date': 'Jun 11', 'time': 'Wed · 7:00pm', 'title': 'Commissioners Cup: Dallas Wings at Phoenix Mercury', 'price': '$36', 'location': ' ·  · PHX Arena ·  ·  · Phoenix, AZ', 'url': '/phoenix-mercury-tickets/wnba/2025-06-11-7-pm/17289899'}
---
{'date': 'Jun 13', 'time': 'Fri · 7:00pm', 'title': 'Commissioners Cup: Dallas Wings at Las Vegas Aces', 'price': '$32', 'location': ' ·  · Michelob ULTRA Arena at Mandalay Bay Resort & Casino ·  ·  · Las Vegas, NV', 'url': '/las-vegas-aces-tickets/wnba/2025-06-13-7-pm/17290383'}
---
{'date': 'Jun 13', 'time': 'Fri · 7:30pm', 'title': 'Commissioners Cup: Chicago Sky at Atlanta Dream', 'price': '$76', 'location': ' ·  · Gateway Center Arena at College Park ·  ·  · College Park, GA', 'url': '/atlanta-dream-tickets/wnba/2025-06-13-7-30-pm/17290116'}
---
{'date': 'Jun 14', 'time': 'Sat · 12:00pm', 'title': 'Commissioners Cup: Los Angeles Sparks at Minnesota Lynx', 'price': '$86', 'location': ' ·  · Target Center ·  ·  · Minneapolis, MN', 'url': '/minnesota-lynx-tickets/wnba/2025-06-14-12-pm/17289905'}
---
{'date': 'Jun 14', 'time': 'Sat · 3:00pm', 'title': 'Commissioners Cup: New York Liberty at Indiana Fever', 'price': '$42', 'location': ' ·  · Gainbridge Fieldhouse ·  ·  · Indianapolis, IN', 'url': '/indiana-fever-tickets/wnba/2025-06-14-3-pm/17290343'}
---
{'date': 'Jun 14', 'time': 'Sat · 5:30pm', 'title': 'Commissioners Cup: Seattle Storm at Golden State Valkyries', 'price': '$33', 'location': ' ·  · Chase Center ·  ·  · San Francisco, CA', 'url': '/golden-state-valkyries-tickets/wnba/2025-06-14-5-30-pm/17290297'}
---

In [15]:
import re
import pandas as pd
from datetime import datetime

# Extract home/away teams
def extract_teams(title: str):
    title_clean = re.sub(r'^[^:]+:\s*', '', title)  # Remove game type prefix if it exists
    if ' at ' in title_clean:
        teams = title_clean.split(' at ', 1)
        away_team, home_team = teams[0].strip(), teams[1].strip()
    elif ' vs ' in title_clean:
        teams = title_clean.split(' vs ', 1)
        home_team, away_team = teams[0].strip(), teams[1].strip()
    else:
        home_team, away_team = None, None
    return home_team, away_team

# Extract game type
def extract_game_type(title: str):
    if ':' in title:
        prefix = title.split(':', 1)[0].strip()
        return prefix.lower().replace(' ', '_')
    else:
        return 'regular_season'

# Extract ticket price
def extract_price(price_str: str):
    match = re.search(r'\$(\d+)', price_str)
    return int(match.group(1)) if match else None

# Parse datetime
def parse_datetime(date_str: str, time_str: str):
    try:
        _, time_part = time_str.split('·')
        time_part = time_part.strip()
        full_str = f"{date_str} {datetime.now().year} {time_part}"
        dt = datetime.strptime(full_str, '%b %d %Y %I:%M%p')
        return dt
    except Exception as e:
        print(f"Error parsing datetime for {date_str} {time_str}: {e}")
        return None

# Build the rows
rows = []

for event in events:
    home_team, away_team = extract_teams(event['title'])
    game_type = extract_game_type(event['title'])
    ticket_price = extract_price(event['price'])
    dt = parse_datetime(event['date'], event['time'])
    
    if dt:
        rows.append({
            'home_team': home_team,
            'away_team': away_team,
            'ticket_price': ticket_price,
            'date': dt.date(),
            'day_of_week': dt.strftime('%A'),
            'time': dt.strftime('%H:%M'),
            'location': event['location'].strip(' ·'),
            'url': event['url'],
            'game_type': game_type,
        })

# Create the DataFrame
df = pd.DataFrame(rows)

In [39]:
# this needs to be done for some manual fixes in xlsx file
# df.to_csv("data/wnba_tickets/wnba_prices.csv", index=False)

In [75]:
df = pd.read_csv("data/wnba_tickets/wnba_prices.csv")
df

,home_team,away_team,ticket_price,date,day_of_week,time,location,url,game_type,duplicate
0,Las Vegas Aces,Dallas Wings,20.0,2025-05-02,Friday,19:00,Purcell Pavilion at the Joyce Center · · · N...,/las-vegas-aces-tickets/wnba/2025-05-02-7-pm/1...,preseason,NaN
1,Chicago Sky,Brazil Womens Basketball National Team,18.0,2025-05-02,Friday,19:00,Pete Maravich Assembly Center · · · Baton Ro...,/chicago-sky-tickets/wnba/2025-05-02-7-pm/1736...,preseason,NaN
2,Indiana Fever,Washington Mystics,10.0,2025-05-03,Saturday,13:00,"Gainbridge Fieldhouse · · · Indianapolis, IN",/indiana-fever-tickets/wnba/2025-05-03-1-pm/17...,preseason,NaN
3,Indiana Fever,Brazil Womens Basketball National Team,146.0,2025-05-04,Sunday,15:00,"Carver-Hawkeye Arena · · · Iowa City, IA",/indiana-fever-tickets/wnba/2025-05-04-3-pm/17...,preseason,NaN
4,Seattle Storm,Connecticut Sun,8.0,2025-05-04,Sunday,15:00,"Climate Pledge Arena · · · Seattle, WA",/seattle-storm-tickets/wnba/2025-05-04-3-pm/17...,preseason,NaN
...,...,...,...,...,...,...,...,...,...,...
296,Connecticut Sun,Atlanta Dream,15.0,2025-09-10,Wednesday,19:00,"Mohegan Sun Arena · · · Uncasville, CT",/connecticut-sun-tickets/wnba/2025-09-10-7-pm/...,regular_season,NaN
297,Chicago Sky,New York Liberty,47.0,2025-09-11,Thursday,19:00,"Wintrust Arena · · · Chicago, IL",/chicago-sky-tickets/wnba/2025-09-11-7-pm/1729...,regular_season,NaN
298,Dallas Wings,Phoenix Mercury,63.0,2025-09-11,Thursday,19:00,"College Park Center · · · Arlington, TX",/dallas-wings-tickets/wnba/2025-09-11-7-pm/172...,regular_season,NaN
299,Minnesota Lynx,Golden State Valkyries,132.0,2025-09-11,Thursday,19:00,"Target Center · · · Minneapolis, MN",/minnesota-lynx-tickets/wnba/2025-09-11-7-pm/1...,regular_season,NaN
300,Los Angeles Sparks,Las Vegas Aces,38.0,2025-09-11,Thursday,19:00,"Crypto.com Arena · · · Los Angeles, CA",/los-angeles-sparks-tickets/wnba/2025-09-11-7-...,regular_season,NaN

In [77]:
# Filter only regular season games
regular_season_df = df[(df['game_type'] == 'regular_season') | (df['game_type'] == 'commissioners_cup')]

# Stack home and away teams into one long column
teams = pd.concat([
    regular_season_df[['home_team', 'ticket_price']].rename(columns={'home_team': 'team'}),
    regular_season_df[['away_team', 'ticket_price']].rename(columns={'away_team': 'team'})
])

# Group by team and calculate the average ticket price
average_price_per_team_regular_season = teams.groupby('team')['ticket_price'].mean().reset_index()

# 2. Average ticket price for each home team (for all games)
average_price_per_home_team = regular_season_df.groupby('home_team')['ticket_price'].mean().reset_index()

# Show the results
print("Average ticket price per team (regular season, home or away):")
print(average_price_per_team_regular_season.sort_values(by='ticket_price', ascending=False))
average_price_per_team_regular_season.sort_values(by='ticket_price', ascending=False).to_csv("data/wnba_tickets/output/average_price.csv")

print("\nAverage ticket price per home team (all games):")
print(average_price_per_home_team.sort_values(by='ticket_price', ascending=False))
average_price_per_home_team.sort_values(by='ticket_price', ascending=False).to_csv("data/wnba_tickets/output/average_home_price.csv")

average_price_per_matchup = regular_season_df.groupby(['home_team', 'away_team'])['ticket_price'].mean().reset_index()

# Show it
print("Average ticket price for each home vs away matchup:")
print(average_price_per_matchup.sort_values(by='ticket_price', ascending=False))
average_price_per_matchup.sort_values(by='ticket_price', ascending=False).to_csv("data/wnba_tickets+output/average_matchup_price.csv")

Average ticket price per team (regular season, home or away):
                      team  ticket_price
3             Dallas Wings     72.636364
8           Minnesota Lynx     68.431818
5            Indiana Fever     68.227273
1              Chicago Sky     52.204545
12      Washington Mystics     51.886364
4   Golden State Valkyries     46.318182
0            Atlanta Dream     43.186047
9         New York Liberty     42.750000
7       Los Angeles Sparks     40.113636
6           Las Vegas Aces     33.568182
2          Connecticut Sun     33.227273
11           Seattle Storm     30.395349
10         Phoenix Mercury     28.954545

Average ticket price per home team (all games):
                 home_team  ticket_price
8           Minnesota Lynx    108.863636
12      Washington Mystics     71.000000
3             Dallas Wings     65.727273
0            Atlanta Dream     60.380952
4   Golden State Valkyries     53.363636
1              Chicago Sky     48.090909
7       Los Angeles Sparks     39.909091
9         New York Liberty     36.227273
2          Connecticut Sun     33.954545
5            Indiana Fever     30.136364
11           Seattle Storm     26.954545
10         Phoenix Mercury     21.363636
6           Las Vegas Aces     17.000000
Average ticket price for each home vs away matchup:
                  home_team           away_team  ticket_price
147      Washington Mystics        Dallas Wings         259.0
101          Minnesota Lynx       Indiana Fever         170.0
2             Atlanta Dream        Dallas Wings         160.0
52   Golden State Valkyries       Indiana Fever         150.5
40             Dallas Wings       Indiana Fever         146.5
..                      ...                 ...           ...
83           Las Vegas Aces  Washington Mystics          12.0
128         Phoenix Mercury      Minnesota Lynx          11.5
74           Las Vegas Aces     Connecticut Sun          10.0
81           Las Vegas Aces     Phoenix Mercury           8.5
72           Las Vegas Aces       Atlanta Dream           7.0

[156 rows x 3 columns]

OSError: Cannot save file into a non-existent directory: 'data/wnba_tickets+output'

In [78]:
# 1. Overall average ticket price (across all regular season + cup games)
overall_avg_price = regular_season_df['ticket_price'].mean()

# 2. Find all unique away teams
away_teams = regular_season_df['away_team'].unique()

# 3. For each away team, calculate their visitor impact
impact_rows = []

for team in away_teams:
    team_games = regular_season_df[regular_season_df['away_team'] == team]
    team_avg_price = team_games['ticket_price'].mean()
    
    if pd.notna(team_avg_price):
        percent_difference = ((team_avg_price - overall_avg_price) / overall_avg_price) * 100
        impact_rows.append({
            'away_team': team,
            'avg_ticket_price_when_visiting': round(team_avg_price, 2),
            'percent_difference_from_overall': round(percent_difference, 2)
        })

# 4. Create a DataFrame
visitor_impact_df = pd.DataFrame(impact_rows)

# 5. Sort by biggest impact
visitor_impact_df = visitor_impact_df.sort_values(by='percent_difference_from_overall', ascending=False)

# 6. Show the final table
visitor_impact_df

visitor_impact_df.to_csv("data/wnba_tickets/output/visitor_impact.csv")

In [79]:
# 1. Create a matchup key that is always Team A vs Team B (sorted alphabetically)
def create_matchup(row):
    teams = sorted([row['home_team'], row['away_team']])
    return f"{teams[0]} vs {teams[1]}"

# Add the matchup column
regular_season_df['matchup'] = regular_season_df.apply(create_matchup, axis=1)

# 2. Group by matchup and calculate average ticket price
matchup_prices = regular_season_df.groupby('matchup')['ticket_price'].mean().reset_index()

# 3. Sort by average price descending
matchup_prices = matchup_prices.sort_values(by='ticket_price', ascending=False)

# 4. Show the most expensive matchup
most_expensive_matchup = matchup_prices.iloc[0]

print(f"The most expensive matchup is {most_expensive_matchup['matchup']} with an average ticket price of ${most_expensive_matchup['ticket_price']:.2f}")

matchup_prices.to_csv("data/wnba_tickets/output/matchup_prices.csv", index=False)

matchup_prices

The most expensive matchup is Dallas Wings vs Washington Mystics with an average ticket price of $123.67

/var/folders/0l/bxmy5l011594gflgwzxxndhr0000gn/T/ipykernel_65274/244174067.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regular_season_df['matchup'] = regular_season_df.apply(create_matchup, axis=1)

                                    matchup  ticket_price
41       Dallas Wings vs Washington Mystics    123.666667
42  Golden State Valkyries vs Indiana Fever    111.000000
2             Atlanta Dream vs Dallas Wings    104.000000
34            Dallas Wings vs Indiana Fever     95.750000
13              Chicago Sky vs Dallas Wings     88.666667
..                                      ...           ...
61          Las Vegas Aces vs Seattle Storm     16.000000
26        Connecticut Sun vs Las Vegas Aces     15.500000
30       Connecticut Sun vs Phoenix Mercury     14.000000
60        Las Vegas Aces vs Phoenix Mercury     13.500000
31         Connecticut Sun vs Seattle Storm     13.500000

[78 rows x 2 columns]

In [74]:
regular_season_df.sort_values(by='ticket_price', ascending=False).tail(10)

# regular_season_df.sort_values(by='ticket_price', ascending=False).to_csv('data/wnba_tickets/output/wnba_prices_sorted.csv', index=False)

,home_team,away_team,ticket_price,date,day_of_week,time,location,url,game_type,duplicate,matchup
256,New York Liberty,Connecticut Sun,10.0,2025-08-25,Monday,19:00,"Barclays Center · · · Brooklyn, NY",/new-york-liberty-tickets/wnba/2025-08-25-7-pm...,regular_season,NaN,Connecticut Sun vs New York Liberty
109,Las Vegas Aces,Washington Mystics,10.0,2025-06-26,Thursday,19:00,Michelob ULTRA Arena at Mandalay Bay Resort & ...,/las-vegas-aces-tickets/wnba/2025-06-26-7-pm/1...,regular_season,NaN,Las Vegas Aces vs Washington Mystics
106,Las Vegas Aces,Connecticut Sun,9.0,2025-06-25,Wednesday,19:00,Michelob ULTRA Arena at Mandalay Bay Resort & ...,/las-vegas-aces-tickets/wnba/2025-06-25-7-pm/1...,regular_season,NaN,Connecticut Sun vs Las Vegas Aces
262,New York Liberty,Washington Mystics,9.0,2025-08-28,Thursday,19:00,"Barclays Center · · · Brooklyn, NY",/new-york-liberty-tickets/wnba/2025-08-28-7-pm...,regular_season,NaN,New York Liberty vs Washington Mystics
286,Connecticut Sun,Phoenix Mercury,8.0,2025-09-06,Saturday,13:00,"Mohegan Sun Arena · · · Uncasville, CT",/connecticut-sun-tickets/wnba/2025-09-06-1-pm/...,regular_season,NaN,Connecticut Sun vs Phoenix Mercury
48,Phoenix Mercury,Minnesota Lynx,8.0,2025-05-30,Friday,19:00,"PHX Arena · · · Phoenix, AZ",/phoenix-mercury-tickets/wnba/2025-05-30-7-pm/...,regular_season,NaN,Minnesota Lynx vs Phoenix Mercury
161,Las Vegas Aces,Atlanta Dream,8.0,2025-07-22,Tuesday,19:00,Michelob ULTRA Arena at Mandalay Bay Resort & ...,/las-vegas-aces-tickets/wnba/2025-07-22-7-pm/1...,regular_season,NaN,Atlanta Dream vs Las Vegas Aces
244,Las Vegas Aces,Phoenix Mercury,6.0,2025-08-21,Thursday,19:00,Michelob ULTRA Arena at Mandalay Bay Resort & ...,/las-vegas-aces-tickets/wnba/2025-08-21-7-pm/1...,regular_season,NaN,Las Vegas Aces vs Phoenix Mercury
240,Las Vegas Aces,Atlanta Dream,6.0,2025-08-19,Tuesday,19:00,Michelob ULTRA Arena at Mandalay Bay Resort & ...,/las-vegas-aces-tickets/wnba/2025-08-19-7-pm/1...,regular_season,NaN,Atlanta Dream vs Las Vegas Aces
229,Seattle Storm,Atlanta Dream,NaN,2025-08-15,Friday,19:00,"Vancouver, Canada",/wnba-canada-game-tickets/wnba/2025-08-15-7-pm...,regular_season,NaN,Atlanta Dream vs Seattle Storm